<?php
//000000007200s:258:"<xml>
<ToUserName><![CDATA[sfdsfdsf]]></ToUserName>
<FromUserName><![CDATA[sfdsfsdf]]></FromUserName>
<CreateTime>1430976717</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[CLICK]]></Event>
<EventKey><![CDATA[dsf]]></EventKey>
</xml>";
?>